import { ConflictError } from "../errors/ConflictError.js";
import * as userRepository from "../repositories/user.repository.js";
// The validated client input for user creation
import type { createUserData } from "../validators/user.validate.js";
import bcrypt from "bcrypt";

export async function createUser(data: createUserData) {
  const existingUser = await userRepository.findByEmployeeId(data.employeeId);

  if (existingUser) {
    throw new ConflictError("Employee ID already exists");
  }

  const hashedPassword = await bcrypt.hash(data.password, 10);

  // We mutated because we changed the zod type for validating client input from
  // passwordHash to password for easy readability but doesnt match db column
  // so for repo we used the type generated by prisma
  const userData = {
    employeeId: data.employeeId,
    firstName: data.firstName,
    lastName: data.lastName,
    passwordHash: hashedPassword,
    role: data.role,
    email: data.email,
  };

  return userRepository.createUser(userData);
}
