import prisma from "../config/prisma.js";
//Used a client input type generated by prisma; which autoupdates after each migration
import type { UserCreateInput } from "../../generated/prisma/models/User.js";

export async function createUser(data: UserCreateInput) {
  return prisma.user.create({
    data,
  });
}

export async function findByEmployeeId(employeeId: string) {
  return prisma.user.findUnique({
    where: {
      employeeId,
    },
  });
}
